azrsh/dotfiles

.github/workflows/ubuntu-test.yml, setup.sh
Reverts azarashi2931/dotfiles#12
=> Revert "Update setup.sh"

remote.sh
=> Fix remote.sh for #34

renovate.json
See also https://docs.renovatebot.com/modules/manager/git-submodules/
=> Enable to update submodules

remote.sh, script/install.sh, script/uninstall.sh, script/update.sh, setup.sh
=> Organize install script

.gitmodules
=> Add assume-chain

script/install.sh, script/update.sh
- tool でインストールしたスクリプトを自動で `chmod +x` する
=> Add auto chmod

.github/workflows/ubuntu-image.yml, .github/workflows/ubuntu-test.yml
=> Fix setup & docker build CI

remote.sh, script/azdot, script/azdot-install, script/azdot-uninstall, script/azdot-update, script/install.sh, setup.sh
- dotfiles を更新するためのスクリプトを `azdot` CLI としてまとめる
=> Add `azdot` CLI

Dockerfile
=> Add dependencies to Dockerfile

script/install.sh
https://github.com/azarashi2931/dotfiles/pull/47 から破壊的な変更を剥がします。
=> BREAKING CHANGE: Remove `install.sh`

.gitmodules
=> Add git-default-branch & git-branch-prune

script/azdot-update
=> Fix `azdot-update` for adding tool

.gitmodules
=> Setup post

config/tmux/.tmux.conf
=> Configure TPM auto install

config/tmux/.tmux.conf
=> tmux: Configure auto window renumbering

.github/workflows/ubuntu-test.yml
=> ci: Clean whitespaces

config/tmux/.tmux.conf
=> tmux: Display session name in status line

script/lib/tool
- tool のインストール時に意図しないファイルまで chmod してしまう問題を修正
=> Fix tool installer

.gitmodules
- Gist から pull した tool を chmod すると diff が出てしまうので無視するよう設定します
=> Ignore submodules dirty

.gitmodules
Azure の VM に SSH するためのユーティリティ、azssh を追加します
=> tool: Add azssh

config/alacritty/.config/alacritty/alacritty.toml
=> config/alacritty: Create

mitamae/cookbooks/alacritty/default.rb, renovate.json
- Utilize custom manager of Renovate
=> mitamae/cookbook/alacritty: Configure Renovate
